# Generated by Django 2.1.5 on 2019-02-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
